config/routes.rb
Rails.application.routes.draw do
    resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
        @task = Task.new
        @tasks = Task.order(id: :desc)
    end

    def create
        t = Task.new(params[:task].permit(:title, :due, :priority, :is_complete, :category))
        t.save
        redirect_to tasks_url
    end

    def edit
        @task = Task.find(params[:id])
        @tasks = Task.order(id: :desc)
        render 'index'
    end

    def update
        task = Task.find(params[:id])
        task.update(params[:task].permit(:title, :due, :priority, :is_complete, :category))
        redirect_to tasks_url
    end

    def destroy
        t = Task.find(params[:id])
        t.destroy
        redirect_to tasks_url
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>Task Manager - alpha</h1>

<%= form_with(model: @task, local: true) do |form| %>
    <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title, id: :task_title %>
    </div>

    <div class="field">
        <%= form.label :is_complete %>
        <%= form.check_box :is_complete, id: :task_is_complete %>
    </div>

    <div class="field">
        <%= form.label :priority %>
        <%= form.number_field :priority, id: :task_priority %>
    </div>

    <div class="field">
        <%= form.label :due %>
        <%= form.date_select :due, id: :task_due %>
    </div>

    <div class="field">
        <%= form.label :category %>
        <%= form.select(:category, id: :task_category) do %>
            <% ['Work', 'Play', 'Home'].each do |cat| %>
                <%= content_tag(:option, cat, value: cat, selected: @task.category == cat) %>
            <% end %>
        <% end %>
    </div>

    <div class="field">
        <%= form.submit %>
    </div>
<% end %>


<table>
    <thead>
        <tr>
            <th></th>
            <th></th>
            <th>complete?</th>
            <th>id</th>
            <th>title</th>
            <th>priority</th>
            <th>category</th>
            <th>due</th>
        </tr>
    </thead>

    <tbody>
        <% @tasks.each do |t| %>
            <tr>
                <td>
                    <%= link_to('edit', edit_task_path(t)) %>
                </td>
                <td>
                    <%= link_to(t, method: :delete) do %>
                        <img width="40" height="40" src="/trash.png" />
                    <% end %>
                </td>
                <td><%= t.is_complete %></td>
                <td><%= t.id %></td>
                <td><%= t.title %></td>
                <td><%= t.priority %></td>
                <td><%= t.category %></td>
                <td><%= t.due %></td>
            </tr>
        <% end %>
    </tbody>
</table>